export const demoProperties = [
  {
    id: "101",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Apartment" },
    rent: 28000,
    bedrooms: 3,
    bathrooms: 3,
    size_sqft: 1450,
    floor: "Floor 4",
    address: "House 42, Road 11, Banani",
    division: "Dhaka",
    availability: true,
    available_from: "2026-08-01",
    description: "Spacious family apartment in Banani, near amenities and public transport.",
    featured: true,
    verified: true,
    dealTag: "AI 89 · Great deal",
  },
  {
    id: "102",
    images: [
      "https://images.unsplash.com/photo-1505691723518-36a58fcb90c5?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Studio" },
    rent: 15000,
    bedrooms: 1,
    bathrooms: 1,
    size_sqft: 520,
    floor: "Floor 2",
    address: "Flat 7A, Road 3, Uttara",
    division: "Dhaka",
    availability: false,
    available_from: "2026-09-10",
    description: "Cozy studio ideal for single professionals. Close to shopping and metro.",
    featured: false,
    verified: false,
    dealTag: "AI 48 · Below avg",
  },
  {
    id: "106",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Duplex" },
    rent: 45000,
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 2200,
    floor: "Floor 6",
    address: "House 12, Road 27, Gulshan",
    division: "Dhaka",
    availability: true,
    available_from: "2026-07-15",
    description: "Luxurious duplex with terrace and city views. High-end finishes.",
    featured: true,
    verified: true,
    dealTag: "AI 92 · Premium",
  },
  {
    id: "103",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Duplex" },
    rent: 45000,
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 2200,
    floor: "Floor 6",
    address: "House 12, Road 27, Gulshan",
    division: "Dhaka",
    availability: true,
    available_from: "2026-07-15",
    description: "Luxurious duplex with terrace and city views. High-end finishes.",
  },
  {
    id: "104",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Duplex" },
    rent: 45000,
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 2200,
    floor: "Floor 6",
    address: "House 12, Road 27, Gulshan",
    division: "Dhaka",
    availability: true,
    available_from: "2026-07-15",
    description: "Luxurious duplex with terrace and city views. High-end finishes.",
  },
  {
    id: "105",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
    ],
    title: "To Let",
    categories: { name: "Duplex" },
    rent: 45000,
    bedrooms: 4,
    bathrooms: 4,
    size_sqft: 2200,
    floor: "Floor 6",
    address: "House 12, Road 27, Gulshan",
    division: "Dhaka",
    availability: true,
    available_from: "2026-07-15",
    description: "Luxurious duplex with terrace and city views. High-end finishes.",
  },
];

export default demoProperties;
